# Uncomment this line to define a global platform for your project

platform :osx, '10.10'

target 'AdaptiveArpRtOsx' do
    pod 'AdaptiveArpImplOsx', '~> 1.0'
end

target 'AdaptiveArpRtOsxTests' do
    pod 'AdaptiveArpImplOsx', '~> 1.0'
end

