# Uncomment this line to define a global platform for your project

target 'AdaptiveArpRtOsx' do
    platform :osx, '10.10'
    pod 'AdaptiveArpImplOsx', '~> 1.0'
end

target 'AdaptiveArpRtOsxTests' do
    platform :osx, '10.10'
    pod 'AdaptiveArpImplOsx', '~> 1.0'
end

