osx_image: beta-xcode6.2
sudo: true
language: objective-c
podfile: adaptive-arp-rt/Podfile

before_install:
- gem install cocoapods

script: 
# fnva (24/04/2015) beta-xcode6.3 pending
- sudo xctool -workspace adaptive-arp-rt/adaptive-arp-rt.xcworkspace -scheme AdaptiveArpRtiOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build
