osx_image: beta-xcode6.2
sudo: false
language: objective-c
podfile: adaptive-arp-rt/Podfile

script: 
- gem install cocoapods --pre
- xctool -workspace adaptive-arp-rt/adaptive-arp-rt.xcworkspace -scheme AdaptiveArpRtiOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test
