sudo: false
language: objective-c
osx_image: xcode611

script: 
- xctool -project adaptive-arp-rt/adaptive-arp-rt.xcodeproj -scheme AdaptiveArpRtOSX -sdk macosx ONLY_ACTIVE_ARCH=NO build
- xctool -project adaptive-arp-rt/adaptive-arp-rt.xcodeproj -scheme AdaptiveArpRtiOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test
