# Uncomment this line to define a global platform for your project

platform :osx, '10.10'

target 'AdaptiveArpImplOsx' do
    pod 'AdaptiveArpApi', '~> 1.0'
end

target 'AdaptiveArpImplOsxTests' do
    pod 'AdaptiveArpApi', '~> 1.0'
end

