# Uncomment this line to define a global platform for your project

target 'AdaptiveArpImplIos' do
    platform :ios, '8.0'
    pod 'AdaptiveArpApi', '~> 1.0'
end

target 'AdaptiveArpImplIosTests' do
    platform :ios, '8.0'
    pod 'AdaptiveArpApi', '~> 1.0'
end

