# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

target 'AdaptiveArpImplIos' do
    pod 'AdaptiveArpApi', '~> 1.0'
end

target 'AdaptiveArpImplIosTests' do
    pod 'AdaptiveArpApi', '~> 1.0'
end

