# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

target 'AdaptiveArpRtIos' do
    pod 'AdaptiveArpImplIos', '~> 1.0'
end

target 'AdaptiveArpRtIosTests' do
    pod 'AdaptiveArpImplIos', '~> 1.0'
end

